best("BB", "heart failure")
best("TX", "heart fai")
best("TX", "heart f")
best("TX", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/tests/testthat/test_errors.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/tests/testthat/test_errors.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/tests/testthat/test_errors.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/tests/testthat/test_errors.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/tests/testthat/test_errors.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/tests/testthat/test_errors.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart failure")
best("TX", "heart attack")
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/tests/testthat/test_best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
detach(df.final)
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
detach(df.final)
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
detach(df.final)
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
df.final
detach(df.final)
head(testdf)
View(testdf)
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
df.clean <- clean.best("Data", "outcome-of-care-measures.csv")
head(df.clean)
head(df.clean %>% mutate(condition = recode(condition, .Mortality.H.Attack = "heart attack",
.Mortality.H.Failure = "heart failure",
.Mortality.Pneumonia = "pneumonia")))
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/data.clean.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/data.clean.R')
head(clean.best("Data", "outcome-of-care-measures.csv", "best" )
)
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/data.clean.R')
head(clean.best("Data", "outcome-of-care-measures.csv","best"))
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/data.clean.R')
head(clean.best("Data", "outcome-of-care-measures.csv","best"))
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/data.clean.R')
head(clean.best("Data", "outcome-of-care-measures.csv","best"))
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/data.clean.R')
head(clean.best("Data", "outcome-of-care-measures.csv","best"))
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/data.clean.R')
head(clean.best("Data", "outcome-of-care-measures.csv","best"))
?mutate
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/data.clean.R')
head(clean.best("Data", "outcome-of-care-measures.csv","best"))
detach(dataset.b)
detach(dataset.b)
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/data.clean.R')
detach(dataset.b)
head(clean.best("Data", "outcome-of-care-measures.csv","best"))
?dplyr::mutate
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/data.clean.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
?desc
search()
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
best("TX", "heart k")
best("gg", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("gg", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("gg", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
setwd("~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment")
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
?assign
tryCatch(stop("xyz"),
error=function(e) {cat("<error>");123L},
finally=cat("<finally>"))
tryCatch(stop("xyz"),
error=function(e) {cat("<error>"},
finally=cat("<finally>"))
tryCatch(stop("xyz"),
error=function(e) {cat("<error>")},
finally=cat("<finally>"))
class(match.arg())
match.arg
pmatch
.Internal(pmatch)
.Internal()
.Internal
.Primitive
best("T", "heart")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "heart")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "heart")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "heart")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "heart")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "heart")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart")
best("TX", "heart attack")
best("TX", "h attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "h attack")
best("T", "h attack")
library(parallel)
detectCores()
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "h attack")
best("TX", "h attack")
foreach(x=list(1, 2, "a"))  %dopar%
{
tryCatch({
c(1/x, x, 2^x)
}, error = function(e) return(paste0("The variable '", x, "'",
" caused the error: '", e, "'")))
}
?%dopar%
foreach(x=list(1, 2, "a"))
{
tryCatch({
c(1/x, x, 2^x)
}, error = function(e) return(paste0("The variable '", x, "'",
" caused the error: '", e, "'")))
}
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "h attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "h attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "h attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "h attack")
best("T", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
sample(LETTERS)
desc(sample(LETTERS))
desc(sample(LETTERS))
l <- sample(LETTERS)
l
desc(l)
desc(l)
l[desc()]
l[desc(l)]
l %>% arrange(desc(l))
head(df.clean)
df.clean %>% arrange(desc(.St))
df.clean %>% arrange(-desc(.St))
df.clean %>% arrange(-desc(.St) & -desc(rate))
df.clean %>% select(.St == "TX") arrange(-desc(.St) & -desc(rate))
df.clean %>% select(.St = "TX") arrange(-desc(.St) & -desc(rate))
df.clean %>% select((.St = "TX")) arrange(-desc(.St) & -desc(rate))
df.clean %>% select(.St = "TX") %>% arrange(-desc(.St) & -desc(rate))
df.clean %>% select(.St) %>% arrange(-desc(.St) & -desc(rate))
df.clean %>% select(.St) %>% arrange(-desc(.St) & -dplyr::desc(rate))
df.clean %>% select(.St) %>% arrange(-desc(.St) & -dplyr::desc(df.clean[["rate"]]))
df.clean %>% select(.St) %>% arrange(-desc(df.clean[[".St"]]) & -dplyr::desc(df.clean[["rate"]]))
df.clean %>% filter(.St = "TX") %>% arrange(-desc(df.clean[[".St"]]) & -dplyr::desc(df.clean[["rate"]]))
df.clean %>% filter(.St == "TX") %>% arrange(-desc(df.clean[[".St"]]) & -dplyr::desc(df.clean[["rate"]]))
df.clean %>% filter(df.clean[[".St]"] == "TX") %>% arrange(-desc(df.clean[[".St"]]) & -dplyr::desc(df.clean[["rate"]]))
df.clean %>% filter(df.clean[[".St"]] == "TX") %>% arrange(-desc(df.clean[[".St"]]) & -dplyr::desc(df.clean[["rate"]]))
df.clean %>% filter(df.clean[[".St"]] == "TX")
df.clean %>% select%1:5) >%(filter(.St == "TX")
)
df.clean %>% select(1:5) >%(filter(.St == "TX")
df.clean %>% select(1:5) %>%(filter(.St == "TX")
df.clean %>% select(1:5) %>%(filter(.St == "TX"))
df.clean %>% select(1:5) %>%(filter(.St == "TX"))
df.clean %>% select(1:5) %>%(filter(df.clean$.St == "TX"))
df.clean %>% select(1:5) %>% filter(df.clean$.St == "TX")
df.clean %>% select(.Hospital, .St, condition, rate) %>% filter(df.clean$.St == "TX")
tail(df.clean %>% select(.Hospital, .St, condition, rate) %>% filter(df.clean$.St == "TX"))
head(df.clean %>% select(.Hospital, .St, condition, rate) %>% filter(df.clean$.St == "TX"))
df.clean %>% dlpyr::filter(df.clean$.St == "TX"))
df.clean %>% dlpyr::filter(df.clean$.St == "TX")
df.clean %>% dplyr::filter(df.clean$.St == "TX")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/tests/testthat/test_best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/tests/testthat/test_best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
count(df.clean$rate)
summarise(df.clean)
summary(df.clean)
df.clean.t <- df.clean %>% transform(rate = as.character(rate))
str(df.clean.t)
count(df.clean.t$rate)
count(df.clean.t[[rate]])
?rle
typeof(df.clean$rate)
class(df.clean$rate)
a <- rle(sort(df.clean$rate))
a
type_of()
type_of(a)
b <- as.data.frame(vl = a$values, ln = a$lengths)
b <- as.data.frame(a, vl = a$values, ln = a$lengths)
b <- data.frame(vl = a$values, ln = a$lengths)
b
df.so <- df.clean %>% filter(df.clean$.St == "TX", df.clean$condition == "heart failure")
df.so <- df.clean %>% filter(df.clean$.St == "TX" & df.clean$condition == "heart failure")
head(df.so)
df.so <- df.clean %>% dplyr::filter(df.clean$.St == "TX" & df.clean$condition == "heart failure")
df.so <- df.clean %>% dplyr::filter(df.clean[[".St"]] == "TX" & df.clean[["condition"]] == "heart failure")
df.so <- df.clean %>% dplyr::filter(df.clean[[".St"]] == c("TX") & df.clean[["condition"]] == c("heart failure"))
head(df.so)
df.so <- df.clean %>% dplyr::filter(df.clean[[".St"]] == c("TX") & df.clean[["condition"]] == c(".Mortality.H.Failure"))
head(df.so)
df.so <- df.clean %>% arrange(-desc(rate))
df.so <- df.clean %>% dplyr::filter(df.clean[[".St"]] == c("TX") & df.clean[["condition"]] == c(".Mortality.H.Failure"))
df.so <- df.so %>% arrange(-desc(rate))
head(df.so)
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/tests/testthat/test_best.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("TX", "heart attack")
best("TX", "heart ")
best("T", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "heart ")
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/best.R')
best("T", "heart ")
cbind
?cbind
b
View(b)
View(a)
a[["values"]]
cbind(a=0, b)
cbind(a=rank(b$vl), b)
b
tt <- cbind(a=rank(b$vl), b)
tt
a
df.so
str(df.so)
tt <- cbind(rank=rank(df.so$rate), tt)
tt <- cbind(rank=rank(df.so$rate), df.so)
tt
tt <- cbind(rank=round(rank(df.so$rate), 0), tt)
tt
tt <- cbind(rank=round(rank(df.so$rate), 0), tt)
tt <- cbind(rank=round(rank(df.so$rate), 0), df.so)
head(tt)
tt <- cbind(rank=round(rank(df.so$rate), 0), df.so)
head(tt)
fr <- rle(sort(tt$rate))
fr
cbind(freq = fr$lengths, tt)
a <- data.frame(vl = fr$values, ln = fr$lengths)
a
min(fr$values)
max(fr$values)
max(fr$values) & max(fr$lengths)
(max(fr$values) & max(fr$lengths))
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/teste_Code_For_Rank_and_freq.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/teste_Code_For_Rank_and_freq.R')
source('~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/teste_Code_For_Rank_and_freq.R')
savehistory("~/projectos/Coursera-R-Programming/Week 4  Simulation and  Profiling/Programming Assignment/history_rank_tests.R")
